name: 🐛 Bug Report
description: Reportar un error o bug encontrado
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the following information to help us address the issue.
  
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe what the bug is.
      placeholder: The system does not allow login when...
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click in '...'
        3. See error
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Should show the user dashboard
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: Shows a 500 error
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this bug?
      options:
        - 🔴 High - Blocks critical functionality
        - 🟡 Medium - Affects functionality but has a workaround
        - 🟢 Low - Minor or cosmetic issue
    validations:
      required: true
  
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Was this bug expected to be found?
      options:
        - Unplanned - Bug found during normal use
        - Planned - Bug detected during testing/QA
    validations:
      required: true
  
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or logs
      description: If applicable, add screenshots or logs of the error
      placeholder: Drag images here or paste logs

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information (browser, version, environment, etc.)

  - type: dropdown
    id: assignees
    attributes:
      label: Assignees
      description: Select who should work on this task (you can select multiple).
      multiple: true
      options:
        - javpalgon
        - celdorrui
        - darzafrui
        - jossilguz
        - Glinbor10
    validations:
      required: true 
