name: 📚 Documentation
description: Suggest improvements or report issues with documentation
title: "[DOCS]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please provide details about the documentation change needed.

  - type: textarea
    id: description
    attributes:
      label: Documentation Issue
      description: What documentation needs to be added, updated, or fixed?
      placeholder: |
        Example:
        - Missing API endpoint documentation for /datasets
        - README installation steps are outdated
        - Typos in contribution guide
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this issue?
      options:
        - 🔴 High - Blocks critical functionality
        - 🟡 Medium - Affects functionality but has a workaround
        - 🟢 Low - Minor or cosmetic issue
    validations:
      required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is this about?
      options:
        - README
        - API Documentation
        - Contributing Guide
        - Code Comments
        - Installation Guide
        - User Guide
        - Other
      default: 0
    validations:
      required: true

  - type: dropdown
    id: assignees
    attributes:
      label: Assignees
      description: Select who should work on this task (you can select multiple).
      multiple: true
      options:
        - javpalgon
        - celdorrui
        - darzafrui
        - jossilguz
        - Glinbor10
    validations:
      required: true 
