name: ✨ Feature Request
description: Solicitar una nueva funcionalidad
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a new feature! Please fill out the following template to help us understand your request better.
  
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see implemented.
      placeholder: English: I would like to have a dark mode option in the settings.
    validations:
      required: true
  
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: How do you suggest implementing this feature?
      placeholder: We could create an email service using SendGrid that ...
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - 🔴 High - Essential for the next release
        - 🟡 Medium - Important but not urgent
        - 🟢 Low - Nice to have
    validations:
      required: true
  
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Was this feature planned?
      options:
        - Planned - Already on the roadmap/backlog
        - Unplanned - New suggestion
    validations:
      required: true

  - type: dropdown
    id: assignees
    attributes:
      label: Assignees
      description: Select who should work on this task (you can select multiple).
      multiple: true
      options:
        - javpalgon
        - celdorrui
        - darzafrui
        - jossilguz
        - Glinbor10
    validations:
      required: true 
